# Generated by Django 5.0.8 on 2024-08-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Titulo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Titulo', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='TipoAtividade',
        ),
    ]
